### ISSUE TITLE
Using set() to get corpus vocab 7.3.1

### ISSUE THREAD

**Issue by ertroyer** [ulfaslak/computational_analysis_of_big_data_2018_spring#10]
I am trying to make a set of all the words from all factions, but for some reason when I take the set of all_words, it suddenly only keeps the unique characters (as shown below). All three faction strings contain appropriate amounts of words, and all_words before turning it into the set appears to in fact contain all of the factions' words.

<img width="1005" alt="screen shot 2018-03-15 at 8 01 46 pm" src="https://user-images.githubusercontent.com/32071201/37485465-d1b21f5a-288b-11e8-90b4-a9158f757698.png">

Any idea why set() is doing this, or how to only get rid of duplicate words not chars?

Here is the code I am referring to for this issue.

```
all_words = list(hero_words) + list(vil_words) + list(amb_words)
#print all_words

all_words = set(all_words)

print all_words
```

**Comment by ulfaslak** [comment]
I think it's because your words are actually a full string. `list` then transforms that into a list of characters. Try to call `.spit()` on your `hero_words`, `vil_words` and `amb_words` before you turn them into lists.
