### ISSUE TITLE
6.2.7 Remove all nodes not in top tens?

### ISSUE THREAD

**Issue by benwestermeyer** [ulfaslak/computational_analysis_of_big_data_2018_spring#11]
I'm unsure about what I should be doing for 6.2.7. It says "we remove all links between nodes that are not on the top 10 list of high-degree characters within their class." Does this mean that we remove all the nodes that are not in the top ten degree lists for their category? That would mean we would just be left with 30 nodes. Is that what we are supposed to do, or am I misinterpreting?

**Comment by ulfaslak** [comment]
Sorry for the last answer. You must loop through all the links and if one of the characters is in the list you keep the link but if both the characters are not you throw it away.
