### ISSUE TITLE
8.2.3 SyntaxError

### ISSUE THREAD

**Issue by ertroyer** [ulfaslak/computational_analysis_of_big_data_2018_spring#14]
Here is the code I have for the first MapReduce sequence.
```
class NumberOfTriangles(MRJob):

    def mapper1(self, _, line):
        lines = line.split()
        all_friends = []
        for j in lines:
            all_friends.append(i)
        all_friends = list(set(all_friends))
        
        for i in all_friends:
            if i==lines[0]:
                yield i, lines[1]
            if i==lines[1]:
                yield i, lines[0]
            else:
                continue
                    
    def reducer1(self, key, values):
        yield key, values
```
I am getting an error that reads "SyntaxError: Non-ASCII character '\xc2' in file ex_8-2-3.py on line 9, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details".

I followed the link and tried all of the proposed solutions, but all that happened is now I get the same error but on line 12 as well.

Any suggestions as to what's going on here?

**Comment by ulfaslak** [comment]
Although a bit convoluted, your code seems almost right. Try using:

```Python
class NumberOfTriangles(MRJob):

    def mapper1(self, _, line):
        nodes = line.split()
        yield nodes[0], nodes[1]
        yield nodes[1], nodes[0]
                    
    def reducer1(self, key, values):
        yield key, list(values)
```

I have no idea what that error is about though.

**Comment by ertroyer** [comment]
Ok I adjusted my code, so now I have this:
```
from mrjob.job import MRJob
from mrjob.step import MRStep

class NumberOfTriangles(MRJob):

    def mapper1(self, _, line):
        nodes = line.split()
        #yield the friendships in both ways--friend 1 to 2 and 2 to 1 on each line
        yield nodes[0], nodes[1]
        yield nodes[1], nodes[0]

    def reducer1(self, key, values):
        yield key, list(values) #must have values accessible in list form

    def mapper2(self, key, values):
        yield key, list(values)

    def reducer2(self, key, values):
        set1 = set(next(values))
        set2 = set(next(values))
        mutual = list(set1 & set2)
        yield key, mutual

    def steps(self):
        return [
            MRStep(
                mapper=self.mapper1,
                reducer=self.reducer1
            ),
            MRStep(
                mapper=self.mapper2,
                reducer=self.reducer2
            )
        ]

if __name__ == '__main__':
    NumberOfTriangles.run()
```

I am now not getting any errors, but I'm also not getting any output. I thought that adjusting mapper2() would take care of the error I was getting after implementing your solution above, which it did, but now it's not giving me anything. The terminal output looks like this:
<img width="569" alt="screen shot 2018-04-04 at 6 14 32 pm" src="https://user-images.githubusercontent.com/32071201/38320154-15e60094-3834-11e8-912f-7dd94990b471.png">

**Comment by ulfaslak** [comment]
Sorry, just saw this. The problem is that your mapper2 is not doing what it is supposed to. Recall that it needs to output key-value pairs that, for one person, are like:
```
([A, B] <person A and her friend B> – [B, C, D] <all of person A's friends>),
([A, C] – [B, C, D]),
([A, D] - [B, C, D])
```
