### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by bradymadden97** [ulfaslak/computational_analysis_of_big_data_2018_spring#2]
When will assignment 1 be posted? Apologies if this was answered in class and I didn't catch it.

**Comment by ulfaslak** [comment]
Thanks for keeping me on my toes! I updated the [Assignments](https://canvas.disabroad.org/courses/1846/pages/assignments) page on Canvas. To answer your question, though, the assignment will be made available shortly after next class ends. You have six days to solve it.
