### ISSUE TITLE
3.2.1 IOError

### ISSUE THREAD

**Issue by ertroyer** [ulfaslak/computational_analysis_of_big_data_2018_spring#3]
This is the code I have so far for 3.2.1:
```python
from collections import Counter
import os

#1. Access the folder
#2. Run through each txt file
#3. Read each line of the txt file, count # words on that line, then add that # to a general count var

all_files = os.listdir("heroes/")
count_hero = 0

for i in all_files:
    if i.endswith('.txt'):
        with open('%s' %i) as fd: #using with makes sure file will close even if something goes wrong w/ method
            wordcount = Counter(i.read().split()) 
        count_hero = count_hero + wordcount
print "test"
```
I'm getting the IOError attached below. It's clearly identifying one of the files (the first, I think?) in the hero folder, any idea why it's saying that the file doesn't exist even though it was pulled from a list of all the files?
<img width="1001" alt="screen shot 2018-02-22 at 11 12 47 pm" src="https://user-images.githubusercontent.com/32071201/36567189-fb94efb2-1825-11e8-9f7b-b4ab39af0c05.png">

**Comment by ulfaslak** [comment]
Well asked question!

I see what's wrong. You're not trying to open the hero file inside the heroes folder. Change this line:

```Python
with open('%s' %i) as fd:
```

to this:

```Python
with open('heroes/%s' %i) as fd:
```

**Comment by ulfaslak** [comment]
Well if you look at what's inside `all_files` (and think about what that error says), `i` is actually a string already.
