### ISSUE TITLE
Testing a "dumb" model

### ISSUE THREAD

**Issue by brookewerner** [ulfaslak/computational_analysis_of_big_data_2018_spring#5]
For question 4.2.1 part 1, how are we supposed to test the baseline accuracy of a "dumb" model? How do we create this dumb model, and how does it differ from the model that we are training on?

**Comment by ulfaslak** [comment]
The "dumb" model is just a baseline to measure against. You don't have to create an actual model, just figure out what its accuracy will be.

To give you a hint the usual baseline is a model that always guesses for the majority class. In this dataset that is villains. So ask yourself: what fraction of guesses do I get right if all my guesses are 'villain'?
